# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  facebook_provider_key: <%= ENV["FACEBOOK_PROVIDER_KEY"] %>
  facebook_provider_secret: <%= ENV["FACEBOOK_PROVIDER_SECRET"] %>
  twitter_provider_key: <%= ENV["TWITTER_PROVIDER_KEY"] %>
  twitter_provider_secret: <%= ENV["TWITTER_PROVIDER_SECRET"] %>
  domain_name: example.com
  secret_key_base: 25065afabab2aedb358ac813142cb4f34a1b48ad57f34af87b61d54e3e224bb0a038143d8c64990fc1e3c56774992a1ae0dc1bcc6d7608861c4f43d7373706ad

test:
  secret_key_base: 25065afabab2aedb358ac813142cb4f34a1b48ad57f34af87b61d54e3e224bb0a038143d8c64990fc1e3c56774992a1ae0dc1bcc6d7608861c4f43d7373706ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  facebook_provider_key: <%= ENV["FACEBOOK_PROVIDER_KEY"] %>
  facebook_provider_secret: <%= ENV["FACEBOOK_PROVIDER_SECRET"] %>
  twitter_provider_key: <%= ENV["TWITTER_PROVIDER_KEY"] %>
  twitter_provider_secret: <%= ENV["TWITTER_PROVIDER_SECRET"] %>
  domain_name: example.com
  secret_key_base: 25065afabab2aedb358ac813142cb4f34a1b48ad57f34af87b61d54e3e224bb0a038143d8c64990fc1e3c56774992a1ae0dc1bcc6d7608861c4f43d7373706ad
