twitter:
  name: 'project x'
  consumer_key: 'hvldXvftPllmmrKkyFUg'
  consumer_secret: '06R1ZpfJEFW8NcG3QvmSB20O926OL1JBRwx5sB3cWRE'
  access_token: '904671-Pek5PdatPbW7m2EtyvBtBi4GtXzpcSNaipQ4k6kxrTw'
  access_token_secret: 'tq7Xk7f70DvlsQvPXTTc5x2F1TaOHWFUOWPfc3ZTL2k'